// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/mittens/v1/optimizer.proto

package mittensv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptimizerService_Optimize_FullMethodName          = "/mittens.v1.OptimizerService/Optimize"
	OptimizerService_StreamTelemetry_FullMethodName   = "/mittens.v1.OptimizerService/StreamTelemetry"
	OptimizerService_StreamTenders_FullMethodName     = "/mittens.v1.OptimizerService/StreamTenders"
	OptimizerService_PlanRepositioning_FullMethodName = "/mittens.v1.OptimizerService/PlanRepositioning"
	OptimizerService_ExplainDecision_FullMethodName   = "/mittens.v1.OptimizerService/ExplainDecision"
	OptimizerService_ReplayDecision_FullMethodName    = "/mittens.v1.OptimizerService/ReplayDecision"
	OptimizerService_VerifyMerkleChain_FullMethodName = "/mittens.v1.OptimizerService/VerifyMerkleChain"
)

// OptimizerServiceClient is the client API for OptimizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OptimizerService provides high-performance binary RPC endpoints for carrier
// fleet dispatch, MOMDP competitor-aware matching, streaming telemetry, and Merkle audits.
type OptimizerServiceClient interface {
	// Optimize executes single-epoch optimal fleet matching via exact LAPJV and Powell policy approximations.
	Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error)
	// StreamTelemetry ingests real-time GPS and ELD Hours-of-Service driver telemetry.
	StreamTelemetry(ctx context.Context, in *StreamTelemetryRequest, opts ...grpc.CallOption) (*StreamTelemetryResponse, error)
	// StreamTenders ingests incoming spot tenders and contract load commitments.
	StreamTenders(ctx context.Context, in *StreamTendersRequest, opts ...grpc.CallOption) (*StreamTendersResponse, error)
	// PlanRepositioning computes empty tractor rebalancing moves across regional nodes.
	PlanRepositioning(ctx context.Context, in *RepositionPlanRequest, opts ...grpc.CallOption) (*RepositionPlanResponse, error)
	// ExplainDecision returns mathematical provenance and marginal attribution for a committed dispatch.
	ExplainDecision(ctx context.Context, in *ExplainDecisionRequest, opts ...grpc.CallOption) (*ExplainDecisionResponse, error)
	// ReplayDecision executes bit-exact deterministic replay of a past optimization epoch.
	ReplayDecision(ctx context.Context, in *ReplayDecisionRequest, opts ...grpc.CallOption) (*ReplayDecisionResponse, error)
	// VerifyMerkleChain cryptographically validates the tamper-evident SHA-256 audit log.
	VerifyMerkleChain(ctx context.Context, in *VerifyMerkleChainRequest, opts ...grpc.CallOption) (*VerifyMerkleChainResponse, error)
}

type optimizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizerServiceClient(cc grpc.ClientConnInterface) OptimizerServiceClient {
	return &optimizerServiceClient{cc}
}

func (c *optimizerServiceClient) Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeResponse)
	err := c.cc.Invoke(ctx, OptimizerService_Optimize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerServiceClient) StreamTelemetry(ctx context.Context, in *StreamTelemetryRequest, opts ...grpc.CallOption) (*StreamTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamTelemetryResponse)
	err := c.cc.Invoke(ctx, OptimizerService_StreamTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerServiceClient) StreamTenders(ctx context.Context, in *StreamTendersRequest, opts ...grpc.CallOption) (*StreamTendersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamTendersResponse)
	err := c.cc.Invoke(ctx, OptimizerService_StreamTenders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerServiceClient) PlanRepositioning(ctx context.Context, in *RepositionPlanRequest, opts ...grpc.CallOption) (*RepositionPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositionPlanResponse)
	err := c.cc.Invoke(ctx, OptimizerService_PlanRepositioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerServiceClient) ExplainDecision(ctx context.Context, in *ExplainDecisionRequest, opts ...grpc.CallOption) (*ExplainDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainDecisionResponse)
	err := c.cc.Invoke(ctx, OptimizerService_ExplainDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerServiceClient) ReplayDecision(ctx context.Context, in *ReplayDecisionRequest, opts ...grpc.CallOption) (*ReplayDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayDecisionResponse)
	err := c.cc.Invoke(ctx, OptimizerService_ReplayDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerServiceClient) VerifyMerkleChain(ctx context.Context, in *VerifyMerkleChainRequest, opts ...grpc.CallOption) (*VerifyMerkleChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyMerkleChainResponse)
	err := c.cc.Invoke(ctx, OptimizerService_VerifyMerkleChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizerServiceServer is the server API for OptimizerService service.
// All implementations must embed UnimplementedOptimizerServiceServer
// for forward compatibility.
//
// OptimizerService provides high-performance binary RPC endpoints for carrier
// fleet dispatch, MOMDP competitor-aware matching, streaming telemetry, and Merkle audits.
type OptimizerServiceServer interface {
	// Optimize executes single-epoch optimal fleet matching via exact LAPJV and Powell policy approximations.
	Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error)
	// StreamTelemetry ingests real-time GPS and ELD Hours-of-Service driver telemetry.
	StreamTelemetry(context.Context, *StreamTelemetryRequest) (*StreamTelemetryResponse, error)
	// StreamTenders ingests incoming spot tenders and contract load commitments.
	StreamTenders(context.Context, *StreamTendersRequest) (*StreamTendersResponse, error)
	// PlanRepositioning computes empty tractor rebalancing moves across regional nodes.
	PlanRepositioning(context.Context, *RepositionPlanRequest) (*RepositionPlanResponse, error)
	// ExplainDecision returns mathematical provenance and marginal attribution for a committed dispatch.
	ExplainDecision(context.Context, *ExplainDecisionRequest) (*ExplainDecisionResponse, error)
	// ReplayDecision executes bit-exact deterministic replay of a past optimization epoch.
	ReplayDecision(context.Context, *ReplayDecisionRequest) (*ReplayDecisionResponse, error)
	// VerifyMerkleChain cryptographically validates the tamper-evident SHA-256 audit log.
	VerifyMerkleChain(context.Context, *VerifyMerkleChainRequest) (*VerifyMerkleChainResponse, error)
	mustEmbedUnimplementedOptimizerServiceServer()
}

// UnimplementedOptimizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizerServiceServer struct{}

func (UnimplementedOptimizerServiceServer) Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Optimize not implemented")
}
func (UnimplementedOptimizerServiceServer) StreamTelemetry(context.Context, *StreamTelemetryRequest) (*StreamTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedOptimizerServiceServer) StreamTenders(context.Context, *StreamTendersRequest) (*StreamTendersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StreamTenders not implemented")
}
func (UnimplementedOptimizerServiceServer) PlanRepositioning(context.Context, *RepositionPlanRequest) (*RepositionPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanRepositioning not implemented")
}
func (UnimplementedOptimizerServiceServer) ExplainDecision(context.Context, *ExplainDecisionRequest) (*ExplainDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainDecision not implemented")
}
func (UnimplementedOptimizerServiceServer) ReplayDecision(context.Context, *ReplayDecisionRequest) (*ReplayDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayDecision not implemented")
}
func (UnimplementedOptimizerServiceServer) VerifyMerkleChain(context.Context, *VerifyMerkleChainRequest) (*VerifyMerkleChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyMerkleChain not implemented")
}
func (UnimplementedOptimizerServiceServer) mustEmbedUnimplementedOptimizerServiceServer() {}
func (UnimplementedOptimizerServiceServer) testEmbeddedByValue()                          {}

// UnsafeOptimizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizerServiceServer will
// result in compilation errors.
type UnsafeOptimizerServiceServer interface {
	mustEmbedUnimplementedOptimizerServiceServer()
}

func RegisterOptimizerServiceServer(s grpc.ServiceRegistrar, srv OptimizerServiceServer) {
	// If the following call panics, it indicates UnimplementedOptimizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptimizerService_ServiceDesc, srv)
}

func _OptimizerService_Optimize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).Optimize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_Optimize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).Optimize(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerService_StreamTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).StreamTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_StreamTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).StreamTelemetry(ctx, req.(*StreamTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerService_StreamTenders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamTendersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).StreamTenders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_StreamTenders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).StreamTenders(ctx, req.(*StreamTendersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerService_PlanRepositioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositionPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).PlanRepositioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_PlanRepositioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).PlanRepositioning(ctx, req.(*RepositionPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerService_ExplainDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).ExplainDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_ExplainDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).ExplainDecision(ctx, req.(*ExplainDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerService_ReplayDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).ReplayDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_ReplayDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).ReplayDecision(ctx, req.(*ReplayDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerService_VerifyMerkleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMerkleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).VerifyMerkleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_VerifyMerkleChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).VerifyMerkleChain(ctx, req.(*VerifyMerkleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OptimizerService_ServiceDesc is the grpc.ServiceDesc for OptimizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptimizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mittens.v1.OptimizerService",
	HandlerType: (*OptimizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Optimize",
			Handler:    _OptimizerService_Optimize_Handler,
		},
		{
			MethodName: "StreamTelemetry",
			Handler:    _OptimizerService_StreamTelemetry_Handler,
		},
		{
			MethodName: "StreamTenders",
			Handler:    _OptimizerService_StreamTenders_Handler,
		},
		{
			MethodName: "PlanRepositioning",
			Handler:    _OptimizerService_PlanRepositioning_Handler,
		},
		{
			MethodName: "ExplainDecision",
			Handler:    _OptimizerService_ExplainDecision_Handler,
		},
		{
			MethodName: "ReplayDecision",
			Handler:    _OptimizerService_ReplayDecision_Handler,
		},
		{
			MethodName: "VerifyMerkleChain",
			Handler:    _OptimizerService_VerifyMerkleChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mittens/v1/optimizer.proto",
}
