// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/mittens/v1/optimizer.proto

package mittensv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Equipment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LengthFeet        float64                `protobuf:"fixed64,2,opt,name=length_feet,json=lengthFeet,proto3" json:"length_feet,omitempty"`
	WeightCapacityLbs float64                `protobuf:"fixed64,3,opt,name=weight_capacity_lbs,json=weightCapacityLbs,proto3" json:"weight_capacity_lbs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Equipment) Reset() {
	*x = Equipment{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Equipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equipment) ProtoMessage() {}

func (x *Equipment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equipment.ProtoReflect.Descriptor instead.
func (*Equipment) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{1}
}

func (x *Equipment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Equipment) GetLengthFeet() float64 {
	if x != nil {
		return x.LengthFeet
	}
	return 0
}

func (x *Equipment) GetWeightCapacityLbs() float64 {
	if x != nil {
		return x.WeightCapacityLbs
	}
	return 0
}

type Driver struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentLocation       *Location              `protobuf:"bytes,2,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	HomeLocation          *Location              `protobuf:"bytes,3,opt,name=home_location,json=homeLocation,proto3" json:"home_location,omitempty"`
	AvailableEpoch        int64                  `protobuf:"varint,4,opt,name=available_epoch,json=availableEpoch,proto3" json:"available_epoch,omitempty"`
	Equipment             *Equipment             `protobuf:"bytes,5,opt,name=equipment,proto3" json:"equipment,omitempty"`
	RemainingDriveHours   float64                `protobuf:"fixed64,6,opt,name=remaining_drive_hours,json=remainingDriveHours,proto3" json:"remaining_drive_hours,omitempty"`
	RemainingDutyHours    float64                `protobuf:"fixed64,7,opt,name=remaining_duty_hours,json=remainingDutyHours,proto3" json:"remaining_duty_hours,omitempty"`
	RemainingCycleHours   float64                `protobuf:"fixed64,8,opt,name=remaining_cycle_hours,json=remainingCycleHours,proto3" json:"remaining_cycle_hours,omitempty"`
	HazmatCertified       bool                   `protobuf:"varint,9,opt,name=hazmat_certified,json=hazmatCertified,proto3" json:"hazmat_certified,omitempty"`
	TeamDriver            bool                   `protobuf:"varint,10,opt,name=team_driver,json=teamDriver,proto3" json:"team_driver,omitempty"`
	DedicatedCustomerId   string                 `protobuf:"bytes,11,opt,name=dedicated_customer_id,json=dedicatedCustomerId,proto3" json:"dedicated_customer_id,omitempty"`
	PreferredDestinations []string               `protobuf:"bytes,12,rep,name=preferred_destinations,json=preferredDestinations,proto3" json:"preferred_destinations,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{2}
}

func (x *Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Driver) GetCurrentLocation() *Location {
	if x != nil {
		return x.CurrentLocation
	}
	return nil
}

func (x *Driver) GetHomeLocation() *Location {
	if x != nil {
		return x.HomeLocation
	}
	return nil
}

func (x *Driver) GetAvailableEpoch() int64 {
	if x != nil {
		return x.AvailableEpoch
	}
	return 0
}

func (x *Driver) GetEquipment() *Equipment {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *Driver) GetRemainingDriveHours() float64 {
	if x != nil {
		return x.RemainingDriveHours
	}
	return 0
}

func (x *Driver) GetRemainingDutyHours() float64 {
	if x != nil {
		return x.RemainingDutyHours
	}
	return 0
}

func (x *Driver) GetRemainingCycleHours() float64 {
	if x != nil {
		return x.RemainingCycleHours
	}
	return 0
}

func (x *Driver) GetHazmatCertified() bool {
	if x != nil {
		return x.HazmatCertified
	}
	return false
}

func (x *Driver) GetTeamDriver() bool {
	if x != nil {
		return x.TeamDriver
	}
	return false
}

func (x *Driver) GetDedicatedCustomerId() string {
	if x != nil {
		return x.DedicatedCustomerId
	}
	return ""
}

func (x *Driver) GetPreferredDestinations() []string {
	if x != nil {
		return x.PreferredDestinations
	}
	return nil
}

type Load struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin                *Location              `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination           *Location              `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	RequiredEquipment     string                 `protobuf:"bytes,4,opt,name=required_equipment,json=requiredEquipment,proto3" json:"required_equipment,omitempty"`
	Revenue               float64                `protobuf:"fixed64,5,opt,name=revenue,proto3" json:"revenue,omitempty"`
	PickupEarliestEpoch   int64                  `protobuf:"varint,6,opt,name=pickup_earliest_epoch,json=pickupEarliestEpoch,proto3" json:"pickup_earliest_epoch,omitempty"`
	PickupLatestEpoch     int64                  `protobuf:"varint,7,opt,name=pickup_latest_epoch,json=pickupLatestEpoch,proto3" json:"pickup_latest_epoch,omitempty"`
	DeliveryEarliestEpoch int64                  `protobuf:"varint,8,opt,name=delivery_earliest_epoch,json=deliveryEarliestEpoch,proto3" json:"delivery_earliest_epoch,omitempty"`
	DeliveryLatestEpoch   int64                  `protobuf:"varint,9,opt,name=delivery_latest_epoch,json=deliveryLatestEpoch,proto3" json:"delivery_latest_epoch,omitempty"`
	WeightLbs             float64                `protobuf:"fixed64,10,opt,name=weight_lbs,json=weightLbs,proto3" json:"weight_lbs,omitempty"`
	Hazmat                bool                   `protobuf:"varint,11,opt,name=hazmat,proto3" json:"hazmat,omitempty"`
	RequiresTeam          bool                   `protobuf:"varint,12,opt,name=requires_team,json=requiresTeam,proto3" json:"requires_team,omitempty"`
	ContractLoad          bool                   `protobuf:"varint,13,opt,name=contract_load,json=contractLoad,proto3" json:"contract_load,omitempty"`
	CustomerId            string                 `protobuf:"bytes,14,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Load) Reset() {
	*x = Load{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Load) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Load) ProtoMessage() {}

func (x *Load) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Load.ProtoReflect.Descriptor instead.
func (*Load) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{3}
}

func (x *Load) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Load) GetOrigin() *Location {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Load) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Load) GetRequiredEquipment() string {
	if x != nil {
		return x.RequiredEquipment
	}
	return ""
}

func (x *Load) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *Load) GetPickupEarliestEpoch() int64 {
	if x != nil {
		return x.PickupEarliestEpoch
	}
	return 0
}

func (x *Load) GetPickupLatestEpoch() int64 {
	if x != nil {
		return x.PickupLatestEpoch
	}
	return 0
}

func (x *Load) GetDeliveryEarliestEpoch() int64 {
	if x != nil {
		return x.DeliveryEarliestEpoch
	}
	return 0
}

func (x *Load) GetDeliveryLatestEpoch() int64 {
	if x != nil {
		return x.DeliveryLatestEpoch
	}
	return 0
}

func (x *Load) GetWeightLbs() float64 {
	if x != nil {
		return x.WeightLbs
	}
	return 0
}

func (x *Load) GetHazmat() bool {
	if x != nil {
		return x.Hazmat
	}
	return false
}

func (x *Load) GetRequiresTeam() bool {
	if x != nil {
		return x.RequiresTeam
	}
	return false
}

func (x *Load) GetContractLoad() bool {
	if x != nil {
		return x.ContractLoad
	}
	return false
}

func (x *Load) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type CostConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	LoadedCostPerMile          float64                `protobuf:"fixed64,1,opt,name=loaded_cost_per_mile,json=loadedCostPerMile,proto3" json:"loaded_cost_per_mile,omitempty"`
	EmptyCostPerMile           float64                `protobuf:"fixed64,2,opt,name=empty_cost_per_mile,json=emptyCostPerMile,proto3" json:"empty_cost_per_mile,omitempty"`
	LatePickupPenaltyPerHour   float64                `protobuf:"fixed64,3,opt,name=late_pickup_penalty_per_hour,json=latePickupPenaltyPerHour,proto3" json:"late_pickup_penalty_per_hour,omitempty"`
	LateDeliveryPenaltyPerHour float64                `protobuf:"fixed64,4,opt,name=late_delivery_penalty_per_hour,json=lateDeliveryPenaltyPerHour,proto3" json:"late_delivery_penalty_per_hour,omitempty"`
	DwellCostPerHour           float64                `protobuf:"fixed64,5,opt,name=dwell_cost_per_hour,json=dwellCostPerHour,proto3" json:"dwell_cost_per_hour,omitempty"`
	LayoverCostPerDay          float64                `protobuf:"fixed64,6,opt,name=layover_cost_per_day,json=layoverCostPerDay,proto3" json:"layover_cost_per_day,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CostConfig) Reset() {
	*x = CostConfig{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostConfig) ProtoMessage() {}

func (x *CostConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostConfig.ProtoReflect.Descriptor instead.
func (*CostConfig) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{4}
}

func (x *CostConfig) GetLoadedCostPerMile() float64 {
	if x != nil {
		return x.LoadedCostPerMile
	}
	return 0
}

func (x *CostConfig) GetEmptyCostPerMile() float64 {
	if x != nil {
		return x.EmptyCostPerMile
	}
	return 0
}

func (x *CostConfig) GetLatePickupPenaltyPerHour() float64 {
	if x != nil {
		return x.LatePickupPenaltyPerHour
	}
	return 0
}

func (x *CostConfig) GetLateDeliveryPenaltyPerHour() float64 {
	if x != nil {
		return x.LateDeliveryPenaltyPerHour
	}
	return 0
}

func (x *CostConfig) GetDwellCostPerHour() float64 {
	if x != nil {
		return x.DwellCostPerHour
	}
	return 0
}

func (x *CostConfig) GetLayoverCostPerDay() float64 {
	if x != nil {
		return x.LayoverCostPerDay
	}
	return 0
}

type FeasibilityConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxEmptyMiles    float64                `protobuf:"fixed64,1,opt,name=max_empty_miles,json=maxEmptyMiles,proto3" json:"max_empty_miles,omitempty"`
	AllowDriverTours bool                   `protobuf:"varint,2,opt,name=allow_driver_tours,json=allowDriverTours,proto3" json:"allow_driver_tours,omitempty"`
	EnforceHos       bool                   `protobuf:"varint,3,opt,name=enforce_hos,json=enforceHos,proto3" json:"enforce_hos,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeasibilityConfig) Reset() {
	*x = FeasibilityConfig{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeasibilityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeasibilityConfig) ProtoMessage() {}

func (x *FeasibilityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeasibilityConfig.ProtoReflect.Descriptor instead.
func (*FeasibilityConfig) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{5}
}

func (x *FeasibilityConfig) GetMaxEmptyMiles() float64 {
	if x != nil {
		return x.MaxEmptyMiles
	}
	return 0
}

func (x *FeasibilityConfig) GetAllowDriverTours() bool {
	if x != nil {
		return x.AllowDriverTours
	}
	return false
}

func (x *FeasibilityConfig) GetEnforceHos() bool {
	if x != nil {
		return x.EnforceHos
	}
	return false
}

type Match struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DriverId              string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	LoadId                string                 `protobuf:"bytes,2,opt,name=load_id,json=loadId,proto3" json:"load_id,omitempty"`
	DispatchEpoch         int64                  `protobuf:"varint,3,opt,name=dispatch_epoch,json=dispatchEpoch,proto3" json:"dispatch_epoch,omitempty"`
	EstimatedContribution float64                `protobuf:"fixed64,4,opt,name=estimated_contribution,json=estimatedContribution,proto3" json:"estimated_contribution,omitempty"`
	EmptyMiles            float64                `protobuf:"fixed64,5,opt,name=empty_miles,json=emptyMiles,proto3" json:"empty_miles,omitempty"`
	LoadedMiles           float64                `protobuf:"fixed64,6,opt,name=loaded_miles,json=loadedMiles,proto3" json:"loaded_miles,omitempty"`
	IsRelay               bool                   `protobuf:"varint,7,opt,name=is_relay,json=isRelay,proto3" json:"is_relay,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{6}
}

func (x *Match) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Match) GetLoadId() string {
	if x != nil {
		return x.LoadId
	}
	return ""
}

func (x *Match) GetDispatchEpoch() int64 {
	if x != nil {
		return x.DispatchEpoch
	}
	return 0
}

func (x *Match) GetEstimatedContribution() float64 {
	if x != nil {
		return x.EstimatedContribution
	}
	return 0
}

func (x *Match) GetEmptyMiles() float64 {
	if x != nil {
		return x.EmptyMiles
	}
	return 0
}

func (x *Match) GetLoadedMiles() float64 {
	if x != nil {
		return x.LoadedMiles
	}
	return 0
}

func (x *Match) GetIsRelay() bool {
	if x != nil {
		return x.IsRelay
	}
	return false
}

type SpotBid struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	LoadId                  string                 `protobuf:"bytes,1,opt,name=load_id,json=loadId,proto3" json:"load_id,omitempty"`
	RatePerMile             float64                `protobuf:"fixed64,2,opt,name=rate_per_mile,json=ratePerMile,proto3" json:"rate_per_mile,omitempty"`
	TotalBidAmount          float64                `protobuf:"fixed64,3,opt,name=total_bid_amount,json=totalBidAmount,proto3" json:"total_bid_amount,omitempty"`
	EstimatedWinProbability float64                `protobuf:"fixed64,4,opt,name=estimated_win_probability,json=estimatedWinProbability,proto3" json:"estimated_win_probability,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SpotBid) Reset() {
	*x = SpotBid{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotBid) ProtoMessage() {}

func (x *SpotBid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotBid.ProtoReflect.Descriptor instead.
func (*SpotBid) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{7}
}

func (x *SpotBid) GetLoadId() string {
	if x != nil {
		return x.LoadId
	}
	return ""
}

func (x *SpotBid) GetRatePerMile() float64 {
	if x != nil {
		return x.RatePerMile
	}
	return 0
}

func (x *SpotBid) GetTotalBidAmount() float64 {
	if x != nil {
		return x.TotalBidAmount
	}
	return 0
}

func (x *SpotBid) GetEstimatedWinProbability() float64 {
	if x != nil {
		return x.EstimatedWinProbability
	}
	return 0
}

type CandidateEvaluation struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DriverId               string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	LoadId                 string                 `protobuf:"bytes,2,opt,name=load_id,json=loadId,proto3" json:"load_id,omitempty"`
	NetContribution        float64                `protobuf:"fixed64,3,opt,name=net_contribution,json=netContribution,proto3" json:"net_contribution,omitempty"`
	PostDecisionStateValue float64                `protobuf:"fixed64,4,opt,name=post_decision_state_value,json=postDecisionStateValue,proto3" json:"post_decision_state_value,omitempty"`
	CompetitorRiskDiscount float64                `protobuf:"fixed64,5,opt,name=competitor_risk_discount,json=competitorRiskDiscount,proto3" json:"competitor_risk_discount,omitempty"`
	TotalScore             float64                `protobuf:"fixed64,6,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	Feasible               bool                   `protobuf:"varint,7,opt,name=feasible,proto3" json:"feasible,omitempty"`
	InfeasibilityReason    string                 `protobuf:"bytes,8,opt,name=infeasibility_reason,json=infeasibilityReason,proto3" json:"infeasibility_reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CandidateEvaluation) Reset() {
	*x = CandidateEvaluation{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateEvaluation) ProtoMessage() {}

func (x *CandidateEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateEvaluation.ProtoReflect.Descriptor instead.
func (*CandidateEvaluation) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{8}
}

func (x *CandidateEvaluation) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CandidateEvaluation) GetLoadId() string {
	if x != nil {
		return x.LoadId
	}
	return ""
}

func (x *CandidateEvaluation) GetNetContribution() float64 {
	if x != nil {
		return x.NetContribution
	}
	return 0
}

func (x *CandidateEvaluation) GetPostDecisionStateValue() float64 {
	if x != nil {
		return x.PostDecisionStateValue
	}
	return 0
}

func (x *CandidateEvaluation) GetCompetitorRiskDiscount() float64 {
	if x != nil {
		return x.CompetitorRiskDiscount
	}
	return 0
}

func (x *CandidateEvaluation) GetTotalScore() float64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *CandidateEvaluation) GetFeasible() bool {
	if x != nil {
		return x.Feasible
	}
	return false
}

func (x *CandidateEvaluation) GetInfeasibilityReason() string {
	if x != nil {
		return x.InfeasibilityReason
	}
	return ""
}

type DecisionProvenance struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OptimizationRunId    string                 `protobuf:"bytes,1,opt,name=optimization_run_id,json=optimizationRunId,proto3" json:"optimization_run_id,omitempty"`
	BatchEpoch           int64                  `protobuf:"varint,2,opt,name=batch_epoch,json=batchEpoch,proto3" json:"batch_epoch,omitempty"`
	PolicyName           string                 `protobuf:"bytes,3,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	ThetaParameters      []float64              `protobuf:"fixed64,4,rep,packed,name=theta_parameters,json=thetaParameters,proto3" json:"theta_parameters,omitempty"`
	EvaluatedArcs        []*CandidateEvaluation `protobuf:"bytes,5,rep,name=evaluated_arcs,json=evaluatedArcs,proto3" json:"evaluated_arcs,omitempty"`
	MatchedCount         int32                  `protobuf:"varint,6,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	TotalNetContribution float64                `protobuf:"fixed64,7,opt,name=total_net_contribution,json=totalNetContribution,proto3" json:"total_net_contribution,omitempty"`
	TotalObjectiveValue  float64                `protobuf:"fixed64,8,opt,name=total_objective_value,json=totalObjectiveValue,proto3" json:"total_objective_value,omitempty"`
	ActiveBeliefVector   map[string]float64     `protobuf:"bytes,9,rep,name=active_belief_vector,json=activeBeliefVector,proto3" json:"active_belief_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	PricingVariables     map[string]float64     `protobuf:"bytes,10,rep,name=pricing_variables,json=pricingVariables,proto3" json:"pricing_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DecisionProvenance) Reset() {
	*x = DecisionProvenance{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionProvenance) ProtoMessage() {}

func (x *DecisionProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionProvenance.ProtoReflect.Descriptor instead.
func (*DecisionProvenance) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{9}
}

func (x *DecisionProvenance) GetOptimizationRunId() string {
	if x != nil {
		return x.OptimizationRunId
	}
	return ""
}

func (x *DecisionProvenance) GetBatchEpoch() int64 {
	if x != nil {
		return x.BatchEpoch
	}
	return 0
}

func (x *DecisionProvenance) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *DecisionProvenance) GetThetaParameters() []float64 {
	if x != nil {
		return x.ThetaParameters
	}
	return nil
}

func (x *DecisionProvenance) GetEvaluatedArcs() []*CandidateEvaluation {
	if x != nil {
		return x.EvaluatedArcs
	}
	return nil
}

func (x *DecisionProvenance) GetMatchedCount() int32 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *DecisionProvenance) GetTotalNetContribution() float64 {
	if x != nil {
		return x.TotalNetContribution
	}
	return 0
}

func (x *DecisionProvenance) GetTotalObjectiveValue() float64 {
	if x != nil {
		return x.TotalObjectiveValue
	}
	return 0
}

func (x *DecisionProvenance) GetActiveBeliefVector() map[string]float64 {
	if x != nil {
		return x.ActiveBeliefVector
	}
	return nil
}

func (x *DecisionProvenance) GetPricingVariables() map[string]float64 {
	if x != nil {
		return x.PricingVariables
	}
	return nil
}

type OptimizeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PolicyClass       string                 `protobuf:"bytes,1,opt,name=policy_class,json=policyClass,proto3" json:"policy_class,omitempty"`             // PFA, CFA, VFA, DLA
	CompetitorScale   string                 `protobuf:"bytes,2,opt,name=competitor_scale,json=competitorScale,proto3" json:"competitor_scale,omitempty"` // N0, N1, N_GENERIC
	Epoch             int64                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Drivers           []*Driver              `protobuf:"bytes,4,rep,name=drivers,proto3" json:"drivers,omitempty"`
	Loads             []*Load                `protobuf:"bytes,5,rep,name=loads,proto3" json:"loads,omitempty"`
	CostConfig        *CostConfig            `protobuf:"bytes,6,opt,name=cost_config,json=costConfig,proto3" json:"cost_config,omitempty"`
	FeasibilityConfig *FeasibilityConfig     `protobuf:"bytes,7,opt,name=feasibility_config,json=feasibilityConfig,proto3" json:"feasibility_config,omitempty"`
	EnableRelays      bool                   `protobuf:"varint,8,opt,name=enable_relays,json=enableRelays,proto3" json:"enable_relays,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{10}
}

func (x *OptimizeRequest) GetPolicyClass() string {
	if x != nil {
		return x.PolicyClass
	}
	return ""
}

func (x *OptimizeRequest) GetCompetitorScale() string {
	if x != nil {
		return x.CompetitorScale
	}
	return ""
}

func (x *OptimizeRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *OptimizeRequest) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *OptimizeRequest) GetLoads() []*Load {
	if x != nil {
		return x.Loads
	}
	return nil
}

func (x *OptimizeRequest) GetCostConfig() *CostConfig {
	if x != nil {
		return x.CostConfig
	}
	return nil
}

func (x *OptimizeRequest) GetFeasibilityConfig() *FeasibilityConfig {
	if x != nil {
		return x.FeasibilityConfig
	}
	return nil
}

func (x *OptimizeRequest) GetEnableRelays() bool {
	if x != nil {
		return x.EnableRelays
	}
	return false
}

type OptimizeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DecisionId           string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	RunId                string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Epoch                int64                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	MatchCount           int32                  `protobuf:"varint,4,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
	Matches              []*Match               `protobuf:"bytes,5,rep,name=matches,proto3" json:"matches,omitempty"`
	SpotBids             []*SpotBid             `protobuf:"bytes,6,rep,name=spot_bids,json=spotBids,proto3" json:"spot_bids,omitempty"`
	TotalNetContribution float64                `protobuf:"fixed64,7,opt,name=total_net_contribution,json=totalNetContribution,proto3" json:"total_net_contribution,omitempty"`
	TotalObjectiveValue  float64                `protobuf:"fixed64,8,opt,name=total_objective_value,json=totalObjectiveValue,proto3" json:"total_objective_value,omitempty"`
	ExecutionDurationMs  float64                `protobuf:"fixed64,9,opt,name=execution_duration_ms,json=executionDurationMs,proto3" json:"execution_duration_ms,omitempty"`
	Provenance           *DecisionProvenance    `protobuf:"bytes,10,opt,name=provenance,proto3" json:"provenance,omitempty"`
	StateHash            string                 `protobuf:"bytes,11,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{11}
}

func (x *OptimizeResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *OptimizeResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *OptimizeResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *OptimizeResponse) GetMatchCount() int32 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

func (x *OptimizeResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *OptimizeResponse) GetSpotBids() []*SpotBid {
	if x != nil {
		return x.SpotBids
	}
	return nil
}

func (x *OptimizeResponse) GetTotalNetContribution() float64 {
	if x != nil {
		return x.TotalNetContribution
	}
	return 0
}

func (x *OptimizeResponse) GetTotalObjectiveValue() float64 {
	if x != nil {
		return x.TotalObjectiveValue
	}
	return 0
}

func (x *OptimizeResponse) GetExecutionDurationMs() float64 {
	if x != nil {
		return x.ExecutionDurationMs
	}
	return 0
}

func (x *OptimizeResponse) GetProvenance() *DecisionProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *OptimizeResponse) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

type StreamTelemetryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DriverId            string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Epoch               int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CurrentLocation     *Location              `protobuf:"bytes,3,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	RemainingDriveHours float64                `protobuf:"fixed64,4,opt,name=remaining_drive_hours,json=remainingDriveHours,proto3" json:"remaining_drive_hours,omitempty"`
	RemainingDutyHours  float64                `protobuf:"fixed64,5,opt,name=remaining_duty_hours,json=remainingDutyHours,proto3" json:"remaining_duty_hours,omitempty"`
	RemainingCycleHours float64                `protobuf:"fixed64,6,opt,name=remaining_cycle_hours,json=remainingCycleHours,proto3" json:"remaining_cycle_hours,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamTelemetryRequest) Reset() {
	*x = StreamTelemetryRequest{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryRequest) ProtoMessage() {}

func (x *StreamTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryRequest.ProtoReflect.Descriptor instead.
func (*StreamTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{12}
}

func (x *StreamTelemetryRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *StreamTelemetryRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *StreamTelemetryRequest) GetCurrentLocation() *Location {
	if x != nil {
		return x.CurrentLocation
	}
	return nil
}

func (x *StreamTelemetryRequest) GetRemainingDriveHours() float64 {
	if x != nil {
		return x.RemainingDriveHours
	}
	return 0
}

func (x *StreamTelemetryRequest) GetRemainingDutyHours() float64 {
	if x != nil {
		return x.RemainingDutyHours
	}
	return 0
}

func (x *StreamTelemetryRequest) GetRemainingCycleHours() float64 {
	if x != nil {
		return x.RemainingCycleHours
	}
	return 0
}

type StreamTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryResponse) Reset() {
	*x = StreamTelemetryResponse{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryResponse) ProtoMessage() {}

func (x *StreamTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryResponse.ProtoReflect.Descriptor instead.
func (*StreamTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{13}
}

func (x *StreamTelemetryResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StreamTelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamTendersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loads         []*Load                `protobuf:"bytes,1,rep,name=loads,proto3" json:"loads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTendersRequest) Reset() {
	*x = StreamTendersRequest{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTendersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTendersRequest) ProtoMessage() {}

func (x *StreamTendersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTendersRequest.ProtoReflect.Descriptor instead.
func (*StreamTendersRequest) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{14}
}

func (x *StreamTendersRequest) GetLoads() []*Load {
	if x != nil {
		return x.Loads
	}
	return nil
}

type StreamTendersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount int32                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTendersResponse) Reset() {
	*x = StreamTendersResponse{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTendersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTendersResponse) ProtoMessage() {}

func (x *StreamTendersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTendersResponse.ProtoReflect.Descriptor instead.
func (*StreamTendersResponse) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{15}
}

func (x *StreamTendersResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *StreamTendersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RepositionPlanRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Epoch                      int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	IdleDrivers                []*Driver              `protobuf:"bytes,2,rep,name=idle_drivers,json=idleDrivers,proto3" json:"idle_drivers,omitempty"`
	TargetRegions              []string               `protobuf:"bytes,3,rep,name=target_regions,json=targetRegions,proto3" json:"target_regions,omitempty"`
	MaxRepositionDistanceMiles float64                `protobuf:"fixed64,4,opt,name=max_reposition_distance_miles,json=maxRepositionDistanceMiles,proto3" json:"max_reposition_distance_miles,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RepositionPlanRequest) Reset() {
	*x = RepositionPlanRequest{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositionPlanRequest) ProtoMessage() {}

func (x *RepositionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositionPlanRequest.ProtoReflect.Descriptor instead.
func (*RepositionPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{16}
}

func (x *RepositionPlanRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RepositionPlanRequest) GetIdleDrivers() []*Driver {
	if x != nil {
		return x.IdleDrivers
	}
	return nil
}

func (x *RepositionPlanRequest) GetTargetRegions() []string {
	if x != nil {
		return x.TargetRegions
	}
	return nil
}

func (x *RepositionPlanRequest) GetMaxRepositionDistanceMiles() float64 {
	if x != nil {
		return x.MaxRepositionDistanceMiles
	}
	return 0
}

type RepositionMove struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	DriverId                    string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OriginRegion                string                 `protobuf:"bytes,2,opt,name=origin_region,json=originRegion,proto3" json:"origin_region,omitempty"`
	DestinationRegion           string                 `protobuf:"bytes,3,opt,name=destination_region,json=destinationRegion,proto3" json:"destination_region,omitempty"`
	EstimatedEmptyMiles         float64                `protobuf:"fixed64,4,opt,name=estimated_empty_miles,json=estimatedEmptyMiles,proto3" json:"estimated_empty_miles,omitempty"`
	ExpectedDownstreamValueLift float64                `protobuf:"fixed64,5,opt,name=expected_downstream_value_lift,json=expectedDownstreamValueLift,proto3" json:"expected_downstream_value_lift,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *RepositionMove) Reset() {
	*x = RepositionMove{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositionMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositionMove) ProtoMessage() {}

func (x *RepositionMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositionMove.ProtoReflect.Descriptor instead.
func (*RepositionMove) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{17}
}

func (x *RepositionMove) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *RepositionMove) GetOriginRegion() string {
	if x != nil {
		return x.OriginRegion
	}
	return ""
}

func (x *RepositionMove) GetDestinationRegion() string {
	if x != nil {
		return x.DestinationRegion
	}
	return ""
}

func (x *RepositionMove) GetEstimatedEmptyMiles() float64 {
	if x != nil {
		return x.EstimatedEmptyMiles
	}
	return 0
}

func (x *RepositionMove) GetExpectedDownstreamValueLift() float64 {
	if x != nil {
		return x.ExpectedDownstreamValueLift
	}
	return 0
}

type RepositionPlanResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MoveCount           int32                  `protobuf:"varint,1,opt,name=move_count,json=moveCount,proto3" json:"move_count,omitempty"`
	Moves               []*RepositionMove      `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	TotalRepositionCost float64                `protobuf:"fixed64,3,opt,name=total_reposition_cost,json=totalRepositionCost,proto3" json:"total_reposition_cost,omitempty"`
	ExpectedNetLift     float64                `protobuf:"fixed64,4,opt,name=expected_net_lift,json=expectedNetLift,proto3" json:"expected_net_lift,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RepositionPlanResponse) Reset() {
	*x = RepositionPlanResponse{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositionPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositionPlanResponse) ProtoMessage() {}

func (x *RepositionPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositionPlanResponse.ProtoReflect.Descriptor instead.
func (*RepositionPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{18}
}

func (x *RepositionPlanResponse) GetMoveCount() int32 {
	if x != nil {
		return x.MoveCount
	}
	return 0
}

func (x *RepositionPlanResponse) GetMoves() []*RepositionMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *RepositionPlanResponse) GetTotalRepositionCost() float64 {
	if x != nil {
		return x.TotalRepositionCost
	}
	return 0
}

func (x *RepositionPlanResponse) GetExpectedNetLift() float64 {
	if x != nil {
		return x.ExpectedNetLift
	}
	return 0
}

type ExplainDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainDecisionRequest) Reset() {
	*x = ExplainDecisionRequest{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainDecisionRequest) ProtoMessage() {}

func (x *ExplainDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainDecisionRequest.ProtoReflect.Descriptor instead.
func (*ExplainDecisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{19}
}

func (x *ExplainDecisionRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type ArcExplanation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DriverId          string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	LoadId            string                 `protobuf:"bytes,2,opt,name=load_id,json=loadId,proto3" json:"load_id,omitempty"`
	BaseRevenue       float64                `protobuf:"fixed64,3,opt,name=base_revenue,json=baseRevenue,proto3" json:"base_revenue,omitempty"`
	TravelCost        float64                `protobuf:"fixed64,4,opt,name=travel_cost,json=travelCost,proto3" json:"travel_cost,omitempty"`
	PostDecisionValue float64                `protobuf:"fixed64,5,opt,name=post_decision_value,json=postDecisionValue,proto3" json:"post_decision_value,omitempty"`
	RiskDiscount      float64                `protobuf:"fixed64,6,opt,name=risk_discount,json=riskDiscount,proto3" json:"risk_discount,omitempty"`
	NetObjective      float64                `protobuf:"fixed64,7,opt,name=net_objective,json=netObjective,proto3" json:"net_objective,omitempty"`
	Selected          bool                   `protobuf:"varint,8,opt,name=selected,proto3" json:"selected,omitempty"`
	ExplanationText   string                 `protobuf:"bytes,9,opt,name=explanation_text,json=explanationText,proto3" json:"explanation_text,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ArcExplanation) Reset() {
	*x = ArcExplanation{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArcExplanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArcExplanation) ProtoMessage() {}

func (x *ArcExplanation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArcExplanation.ProtoReflect.Descriptor instead.
func (*ArcExplanation) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{20}
}

func (x *ArcExplanation) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ArcExplanation) GetLoadId() string {
	if x != nil {
		return x.LoadId
	}
	return ""
}

func (x *ArcExplanation) GetBaseRevenue() float64 {
	if x != nil {
		return x.BaseRevenue
	}
	return 0
}

func (x *ArcExplanation) GetTravelCost() float64 {
	if x != nil {
		return x.TravelCost
	}
	return 0
}

func (x *ArcExplanation) GetPostDecisionValue() float64 {
	if x != nil {
		return x.PostDecisionValue
	}
	return 0
}

func (x *ArcExplanation) GetRiskDiscount() float64 {
	if x != nil {
		return x.RiskDiscount
	}
	return 0
}

func (x *ArcExplanation) GetNetObjective() float64 {
	if x != nil {
		return x.NetObjective
	}
	return 0
}

func (x *ArcExplanation) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *ArcExplanation) GetExplanationText() string {
	if x != nil {
		return x.ExplanationText
	}
	return ""
}

type ExplainDecisionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DecisionId         string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	PolicyClass        string                 `protobuf:"bytes,2,opt,name=policy_class,json=policyClass,proto3" json:"policy_class,omitempty"`
	EvaluatedArcsCount int32                  `protobuf:"varint,3,opt,name=evaluated_arcs_count,json=evaluatedArcsCount,proto3" json:"evaluated_arcs_count,omitempty"`
	TopCandidates      []*ArcExplanation      `protobuf:"bytes,4,rep,name=top_candidates,json=topCandidates,proto3" json:"top_candidates,omitempty"`
	MarkdownSummary    string                 `protobuf:"bytes,5,opt,name=markdown_summary,json=markdownSummary,proto3" json:"markdown_summary,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExplainDecisionResponse) Reset() {
	*x = ExplainDecisionResponse{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainDecisionResponse) ProtoMessage() {}

func (x *ExplainDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainDecisionResponse.ProtoReflect.Descriptor instead.
func (*ExplainDecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{21}
}

func (x *ExplainDecisionResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *ExplainDecisionResponse) GetPolicyClass() string {
	if x != nil {
		return x.PolicyClass
	}
	return ""
}

func (x *ExplainDecisionResponse) GetEvaluatedArcsCount() int32 {
	if x != nil {
		return x.EvaluatedArcsCount
	}
	return 0
}

func (x *ExplainDecisionResponse) GetTopCandidates() []*ArcExplanation {
	if x != nil {
		return x.TopCandidates
	}
	return nil
}

func (x *ExplainDecisionResponse) GetMarkdownSummary() string {
	if x != nil {
		return x.MarkdownSummary
	}
	return ""
}

type ReplayDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDecisionRequest) Reset() {
	*x = ReplayDecisionRequest{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDecisionRequest) ProtoMessage() {}

func (x *ReplayDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDecisionRequest.ProtoReflect.Descriptor instead.
func (*ReplayDecisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{22}
}

func (x *ReplayDecisionRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type ReplayDecisionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DecisionId            string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Status                string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // BIT_EXACT_MATCH, DIVERGENCE_DETECTED
	DriftAmount           float64                `protobuf:"fixed64,3,opt,name=drift_amount,json=driftAmount,proto3" json:"drift_amount,omitempty"`
	InitialStateHashMatch bool                   `protobuf:"varint,4,opt,name=initial_state_hash_match,json=initialStateHashMatch,proto3" json:"initial_state_hash_match,omitempty"`
	ActionHashMatch       bool                   `protobuf:"varint,5,opt,name=action_hash_match,json=actionHashMatch,proto3" json:"action_hash_match,omitempty"`
	Details               string                 `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReplayDecisionResponse) Reset() {
	*x = ReplayDecisionResponse{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDecisionResponse) ProtoMessage() {}

func (x *ReplayDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDecisionResponse.ProtoReflect.Descriptor instead.
func (*ReplayDecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{23}
}

func (x *ReplayDecisionResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *ReplayDecisionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReplayDecisionResponse) GetDriftAmount() float64 {
	if x != nil {
		return x.DriftAmount
	}
	return 0
}

func (x *ReplayDecisionResponse) GetInitialStateHashMatch() bool {
	if x != nil {
		return x.InitialStateHashMatch
	}
	return false
}

func (x *ReplayDecisionResponse) GetActionHashMatch() bool {
	if x != nil {
		return x.ActionHashMatch
	}
	return false
}

func (x *ReplayDecisionResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type VerifyMerkleChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMerkleChainRequest) Reset() {
	*x = VerifyMerkleChainRequest{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMerkleChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMerkleChainRequest) ProtoMessage() {}

func (x *VerifyMerkleChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMerkleChainRequest.ProtoReflect.Descriptor instead.
func (*VerifyMerkleChainRequest) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{24}
}

func (x *VerifyMerkleChainRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type VerifyMerkleChainResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RunId                string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	IsValid              bool                   `protobuf:"varint,2,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	TotalRecordsVerified int64                  `protobuf:"varint,3,opt,name=total_records_verified,json=totalRecordsVerified,proto3" json:"total_records_verified,omitempty"`
	LatestRecordHash     string                 `protobuf:"bytes,4,opt,name=latest_record_hash,json=latestRecordHash,proto3" json:"latest_record_hash,omitempty"`
	VerificationMessage  string                 `protobuf:"bytes,5,opt,name=verification_message,json=verificationMessage,proto3" json:"verification_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VerifyMerkleChainResponse) Reset() {
	*x = VerifyMerkleChainResponse{}
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMerkleChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMerkleChainResponse) ProtoMessage() {}

func (x *VerifyMerkleChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mittens_v1_optimizer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMerkleChainResponse.ProtoReflect.Descriptor instead.
func (*VerifyMerkleChainResponse) Descriptor() ([]byte, []int) {
	return file_proto_mittens_v1_optimizer_proto_rawDescGZIP(), []int{25}
}

func (x *VerifyMerkleChainResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *VerifyMerkleChainResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifyMerkleChainResponse) GetTotalRecordsVerified() int64 {
	if x != nil {
		return x.TotalRecordsVerified
	}
	return 0
}

func (x *VerifyMerkleChainResponse) GetLatestRecordHash() string {
	if x != nil {
		return x.LatestRecordHash
	}
	return ""
}

func (x *VerifyMerkleChainResponse) GetVerificationMessage() string {
	if x != nil {
		return x.VerificationMessage
	}
	return ""
}

var File_proto_mittens_v1_optimizer_proto protoreflect.FileDescriptor

const file_proto_mittens_v1_optimizer_proto_rawDesc = "" +
	"\n" +
	" proto/mittens/v1/optimizer.proto\x12\n" +
	"mittens.v1\"G\n" +
	"\bLocation\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\"p\n" +
	"\tEquipment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vlength_feet\x18\x02 \x01(\x01R\n" +
	"lengthFeet\x12.\n" +
	"\x13weight_capacity_lbs\x18\x03 \x01(\x01R\x11weightCapacityLbs\"\xc3\x04\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\x10current_location\x18\x02 \x01(\v2\x14.mittens.v1.LocationR\x0fcurrentLocation\x129\n" +
	"\rhome_location\x18\x03 \x01(\v2\x14.mittens.v1.LocationR\fhomeLocation\x12'\n" +
	"\x0favailable_epoch\x18\x04 \x01(\x03R\x0eavailableEpoch\x123\n" +
	"\tequipment\x18\x05 \x01(\v2\x15.mittens.v1.EquipmentR\tequipment\x122\n" +
	"\x15remaining_drive_hours\x18\x06 \x01(\x01R\x13remainingDriveHours\x120\n" +
	"\x14remaining_duty_hours\x18\a \x01(\x01R\x12remainingDutyHours\x122\n" +
	"\x15remaining_cycle_hours\x18\b \x01(\x01R\x13remainingCycleHours\x12)\n" +
	"\x10hazmat_certified\x18\t \x01(\bR\x0fhazmatCertified\x12\x1f\n" +
	"\vteam_driver\x18\n" +
	" \x01(\bR\n" +
	"teamDriver\x122\n" +
	"\x15dedicated_customer_id\x18\v \x01(\tR\x13dedicatedCustomerId\x125\n" +
	"\x16preferred_destinations\x18\f \x03(\tR\x15preferredDestinations\"\xb7\x04\n" +
	"\x04Load\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x06origin\x18\x02 \x01(\v2\x14.mittens.v1.LocationR\x06origin\x126\n" +
	"\vdestination\x18\x03 \x01(\v2\x14.mittens.v1.LocationR\vdestination\x12-\n" +
	"\x12required_equipment\x18\x04 \x01(\tR\x11requiredEquipment\x12\x18\n" +
	"\arevenue\x18\x05 \x01(\x01R\arevenue\x122\n" +
	"\x15pickup_earliest_epoch\x18\x06 \x01(\x03R\x13pickupEarliestEpoch\x12.\n" +
	"\x13pickup_latest_epoch\x18\a \x01(\x03R\x11pickupLatestEpoch\x126\n" +
	"\x17delivery_earliest_epoch\x18\b \x01(\x03R\x15deliveryEarliestEpoch\x122\n" +
	"\x15delivery_latest_epoch\x18\t \x01(\x03R\x13deliveryLatestEpoch\x12\x1d\n" +
	"\n" +
	"weight_lbs\x18\n" +
	" \x01(\x01R\tweightLbs\x12\x16\n" +
	"\x06hazmat\x18\v \x01(\bR\x06hazmat\x12#\n" +
	"\rrequires_team\x18\f \x01(\bR\frequiresTeam\x12#\n" +
	"\rcontract_load\x18\r \x01(\bR\fcontractLoad\x12\x1f\n" +
	"\vcustomer_id\x18\x0e \x01(\tR\n" +
	"customerId\"\xd0\x02\n" +
	"\n" +
	"CostConfig\x12/\n" +
	"\x14loaded_cost_per_mile\x18\x01 \x01(\x01R\x11loadedCostPerMile\x12-\n" +
	"\x13empty_cost_per_mile\x18\x02 \x01(\x01R\x10emptyCostPerMile\x12>\n" +
	"\x1clate_pickup_penalty_per_hour\x18\x03 \x01(\x01R\x18latePickupPenaltyPerHour\x12B\n" +
	"\x1elate_delivery_penalty_per_hour\x18\x04 \x01(\x01R\x1alateDeliveryPenaltyPerHour\x12-\n" +
	"\x13dwell_cost_per_hour\x18\x05 \x01(\x01R\x10dwellCostPerHour\x12/\n" +
	"\x14layover_cost_per_day\x18\x06 \x01(\x01R\x11layoverCostPerDay\"\x8a\x01\n" +
	"\x11FeasibilityConfig\x12&\n" +
	"\x0fmax_empty_miles\x18\x01 \x01(\x01R\rmaxEmptyMiles\x12,\n" +
	"\x12allow_driver_tours\x18\x02 \x01(\bR\x10allowDriverTours\x12\x1f\n" +
	"\venforce_hos\x18\x03 \x01(\bR\n" +
	"enforceHos\"\xfa\x01\n" +
	"\x05Match\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\aload_id\x18\x02 \x01(\tR\x06loadId\x12%\n" +
	"\x0edispatch_epoch\x18\x03 \x01(\x03R\rdispatchEpoch\x125\n" +
	"\x16estimated_contribution\x18\x04 \x01(\x01R\x15estimatedContribution\x12\x1f\n" +
	"\vempty_miles\x18\x05 \x01(\x01R\n" +
	"emptyMiles\x12!\n" +
	"\floaded_miles\x18\x06 \x01(\x01R\vloadedMiles\x12\x19\n" +
	"\bis_relay\x18\a \x01(\bR\aisRelay\"\xac\x01\n" +
	"\aSpotBid\x12\x17\n" +
	"\aload_id\x18\x01 \x01(\tR\x06loadId\x12\"\n" +
	"\rrate_per_mile\x18\x02 \x01(\x01R\vratePerMile\x12(\n" +
	"\x10total_bid_amount\x18\x03 \x01(\x01R\x0etotalBidAmount\x12:\n" +
	"\x19estimated_win_probability\x18\x04 \x01(\x01R\x17estimatedWinProbability\"\xdb\x02\n" +
	"\x13CandidateEvaluation\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\aload_id\x18\x02 \x01(\tR\x06loadId\x12)\n" +
	"\x10net_contribution\x18\x03 \x01(\x01R\x0fnetContribution\x129\n" +
	"\x19post_decision_state_value\x18\x04 \x01(\x01R\x16postDecisionStateValue\x128\n" +
	"\x18competitor_risk_discount\x18\x05 \x01(\x01R\x16competitorRiskDiscount\x12\x1f\n" +
	"\vtotal_score\x18\x06 \x01(\x01R\n" +
	"totalScore\x12\x1a\n" +
	"\bfeasible\x18\a \x01(\bR\bfeasible\x121\n" +
	"\x14infeasibility_reason\x18\b \x01(\tR\x13infeasibilityReason\"\xe1\x05\n" +
	"\x12DecisionProvenance\x12.\n" +
	"\x13optimization_run_id\x18\x01 \x01(\tR\x11optimizationRunId\x12\x1f\n" +
	"\vbatch_epoch\x18\x02 \x01(\x03R\n" +
	"batchEpoch\x12\x1f\n" +
	"\vpolicy_name\x18\x03 \x01(\tR\n" +
	"policyName\x12)\n" +
	"\x10theta_parameters\x18\x04 \x03(\x01R\x0fthetaParameters\x12F\n" +
	"\x0eevaluated_arcs\x18\x05 \x03(\v2\x1f.mittens.v1.CandidateEvaluationR\revaluatedArcs\x12#\n" +
	"\rmatched_count\x18\x06 \x01(\x05R\fmatchedCount\x124\n" +
	"\x16total_net_contribution\x18\a \x01(\x01R\x14totalNetContribution\x122\n" +
	"\x15total_objective_value\x18\b \x01(\x01R\x13totalObjectiveValue\x12h\n" +
	"\x14active_belief_vector\x18\t \x03(\v26.mittens.v1.DecisionProvenance.ActiveBeliefVectorEntryR\x12activeBeliefVector\x12a\n" +
	"\x11pricing_variables\x18\n" +
	" \x03(\v24.mittens.v1.DecisionProvenance.PricingVariablesEntryR\x10pricingVariables\x1aE\n" +
	"\x17ActiveBeliefVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aC\n" +
	"\x15PricingVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xf7\x02\n" +
	"\x0fOptimizeRequest\x12!\n" +
	"\fpolicy_class\x18\x01 \x01(\tR\vpolicyClass\x12)\n" +
	"\x10competitor_scale\x18\x02 \x01(\tR\x0fcompetitorScale\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\x12,\n" +
	"\adrivers\x18\x04 \x03(\v2\x12.mittens.v1.DriverR\adrivers\x12&\n" +
	"\x05loads\x18\x05 \x03(\v2\x10.mittens.v1.LoadR\x05loads\x127\n" +
	"\vcost_config\x18\x06 \x01(\v2\x16.mittens.v1.CostConfigR\n" +
	"costConfig\x12L\n" +
	"\x12feasibility_config\x18\a \x01(\v2\x1d.mittens.v1.FeasibilityConfigR\x11feasibilityConfig\x12#\n" +
	"\renable_relays\x18\b \x01(\bR\fenableRelays\"\xdd\x03\n" +
	"\x10OptimizeResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\x12\x1f\n" +
	"\vmatch_count\x18\x04 \x01(\x05R\n" +
	"matchCount\x12+\n" +
	"\amatches\x18\x05 \x03(\v2\x11.mittens.v1.MatchR\amatches\x120\n" +
	"\tspot_bids\x18\x06 \x03(\v2\x13.mittens.v1.SpotBidR\bspotBids\x124\n" +
	"\x16total_net_contribution\x18\a \x01(\x01R\x14totalNetContribution\x122\n" +
	"\x15total_objective_value\x18\b \x01(\x01R\x13totalObjectiveValue\x122\n" +
	"\x15execution_duration_ms\x18\t \x01(\x01R\x13executionDurationMs\x12>\n" +
	"\n" +
	"provenance\x18\n" +
	" \x01(\v2\x1e.mittens.v1.DecisionProvenanceR\n" +
	"provenance\x12\x1d\n" +
	"\n" +
	"state_hash\x18\v \x01(\tR\tstateHash\"\xa6\x02\n" +
	"\x16StreamTelemetryRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12?\n" +
	"\x10current_location\x18\x03 \x01(\v2\x14.mittens.v1.LocationR\x0fcurrentLocation\x122\n" +
	"\x15remaining_drive_hours\x18\x04 \x01(\x01R\x13remainingDriveHours\x120\n" +
	"\x14remaining_duty_hours\x18\x05 \x01(\x01R\x12remainingDutyHours\x122\n" +
	"\x15remaining_cycle_hours\x18\x06 \x01(\x01R\x13remainingCycleHours\"O\n" +
	"\x17StreamTelemetryResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x14StreamTendersRequest\x12&\n" +
	"\x05loads\x18\x01 \x03(\v2\x10.mittens.v1.LoadR\x05loads\"X\n" +
	"\x15StreamTendersResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xce\x01\n" +
	"\x15RepositionPlanRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x125\n" +
	"\fidle_drivers\x18\x02 \x03(\v2\x12.mittens.v1.DriverR\vidleDrivers\x12%\n" +
	"\x0etarget_regions\x18\x03 \x03(\tR\rtargetRegions\x12A\n" +
	"\x1dmax_reposition_distance_miles\x18\x04 \x01(\x01R\x1amaxRepositionDistanceMiles\"\xfa\x01\n" +
	"\x0eRepositionMove\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12#\n" +
	"\rorigin_region\x18\x02 \x01(\tR\foriginRegion\x12-\n" +
	"\x12destination_region\x18\x03 \x01(\tR\x11destinationRegion\x122\n" +
	"\x15estimated_empty_miles\x18\x04 \x01(\x01R\x13estimatedEmptyMiles\x12C\n" +
	"\x1eexpected_downstream_value_lift\x18\x05 \x01(\x01R\x1bexpectedDownstreamValueLift\"\xc9\x01\n" +
	"\x16RepositionPlanResponse\x12\x1d\n" +
	"\n" +
	"move_count\x18\x01 \x01(\x05R\tmoveCount\x120\n" +
	"\x05moves\x18\x02 \x03(\v2\x1a.mittens.v1.RepositionMoveR\x05moves\x122\n" +
	"\x15total_reposition_cost\x18\x03 \x01(\x01R\x13totalRepositionCost\x12*\n" +
	"\x11expected_net_lift\x18\x04 \x01(\x01R\x0fexpectedNetLift\"9\n" +
	"\x16ExplainDecisionRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\"\xcb\x02\n" +
	"\x0eArcExplanation\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\aload_id\x18\x02 \x01(\tR\x06loadId\x12!\n" +
	"\fbase_revenue\x18\x03 \x01(\x01R\vbaseRevenue\x12\x1f\n" +
	"\vtravel_cost\x18\x04 \x01(\x01R\n" +
	"travelCost\x12.\n" +
	"\x13post_decision_value\x18\x05 \x01(\x01R\x11postDecisionValue\x12#\n" +
	"\rrisk_discount\x18\x06 \x01(\x01R\friskDiscount\x12#\n" +
	"\rnet_objective\x18\a \x01(\x01R\fnetObjective\x12\x1a\n" +
	"\bselected\x18\b \x01(\bR\bselected\x12)\n" +
	"\x10explanation_text\x18\t \x01(\tR\x0fexplanationText\"\xfd\x01\n" +
	"\x17ExplainDecisionResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12!\n" +
	"\fpolicy_class\x18\x02 \x01(\tR\vpolicyClass\x120\n" +
	"\x14evaluated_arcs_count\x18\x03 \x01(\x05R\x12evaluatedArcsCount\x12A\n" +
	"\x0etop_candidates\x18\x04 \x03(\v2\x1a.mittens.v1.ArcExplanationR\rtopCandidates\x12)\n" +
	"\x10markdown_summary\x18\x05 \x01(\tR\x0fmarkdownSummary\"8\n" +
	"\x15ReplayDecisionRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\"\xf3\x01\n" +
	"\x16ReplayDecisionResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fdrift_amount\x18\x03 \x01(\x01R\vdriftAmount\x127\n" +
	"\x18initial_state_hash_match\x18\x04 \x01(\bR\x15initialStateHashMatch\x12*\n" +
	"\x11action_hash_match\x18\x05 \x01(\bR\x0factionHashMatch\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\"1\n" +
	"\x18VerifyMerkleChainRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xe4\x01\n" +
	"\x19VerifyMerkleChainResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\bis_valid\x18\x02 \x01(\bR\aisValid\x124\n" +
	"\x16total_records_verified\x18\x03 \x01(\x03R\x14totalRecordsVerified\x12,\n" +
	"\x12latest_record_hash\x18\x04 \x01(\tR\x10latestRecordHash\x121\n" +
	"\x14verification_message\x18\x05 \x01(\tR\x13verificationMessage2\xfe\x04\n" +
	"\x10OptimizerService\x12E\n" +
	"\bOptimize\x12\x1b.mittens.v1.OptimizeRequest\x1a\x1c.mittens.v1.OptimizeResponse\x12Z\n" +
	"\x0fStreamTelemetry\x12\".mittens.v1.StreamTelemetryRequest\x1a#.mittens.v1.StreamTelemetryResponse\x12T\n" +
	"\rStreamTenders\x12 .mittens.v1.StreamTendersRequest\x1a!.mittens.v1.StreamTendersResponse\x12Z\n" +
	"\x11PlanRepositioning\x12!.mittens.v1.RepositionPlanRequest\x1a\".mittens.v1.RepositionPlanResponse\x12Z\n" +
	"\x0fExplainDecision\x12\".mittens.v1.ExplainDecisionRequest\x1a#.mittens.v1.ExplainDecisionResponse\x12W\n" +
	"\x0eReplayDecision\x12!.mittens.v1.ReplayDecisionRequest\x1a\".mittens.v1.ReplayDecisionResponse\x12`\n" +
	"\x11VerifyMerkleChain\x12$.mittens.v1.VerifyMerkleChainRequest\x1a%.mittens.v1.VerifyMerkleChainResponseBGZEgithub.com/optimaldynamics/project-mittens/proto/mittens/v1;mittensv1b\x06proto3"

var (
	file_proto_mittens_v1_optimizer_proto_rawDescOnce sync.Once
	file_proto_mittens_v1_optimizer_proto_rawDescData []byte
)

func file_proto_mittens_v1_optimizer_proto_rawDescGZIP() []byte {
	file_proto_mittens_v1_optimizer_proto_rawDescOnce.Do(func() {
		file_proto_mittens_v1_optimizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mittens_v1_optimizer_proto_rawDesc), len(file_proto_mittens_v1_optimizer_proto_rawDesc)))
	})
	return file_proto_mittens_v1_optimizer_proto_rawDescData
}

var file_proto_mittens_v1_optimizer_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_mittens_v1_optimizer_proto_goTypes = []any{
	(*Location)(nil),                  // 0: mittens.v1.Location
	(*Equipment)(nil),                 // 1: mittens.v1.Equipment
	(*Driver)(nil),                    // 2: mittens.v1.Driver
	(*Load)(nil),                      // 3: mittens.v1.Load
	(*CostConfig)(nil),                // 4: mittens.v1.CostConfig
	(*FeasibilityConfig)(nil),         // 5: mittens.v1.FeasibilityConfig
	(*Match)(nil),                     // 6: mittens.v1.Match
	(*SpotBid)(nil),                   // 7: mittens.v1.SpotBid
	(*CandidateEvaluation)(nil),       // 8: mittens.v1.CandidateEvaluation
	(*DecisionProvenance)(nil),        // 9: mittens.v1.DecisionProvenance
	(*OptimizeRequest)(nil),           // 10: mittens.v1.OptimizeRequest
	(*OptimizeResponse)(nil),          // 11: mittens.v1.OptimizeResponse
	(*StreamTelemetryRequest)(nil),    // 12: mittens.v1.StreamTelemetryRequest
	(*StreamTelemetryResponse)(nil),   // 13: mittens.v1.StreamTelemetryResponse
	(*StreamTendersRequest)(nil),      // 14: mittens.v1.StreamTendersRequest
	(*StreamTendersResponse)(nil),     // 15: mittens.v1.StreamTendersResponse
	(*RepositionPlanRequest)(nil),     // 16: mittens.v1.RepositionPlanRequest
	(*RepositionMove)(nil),            // 17: mittens.v1.RepositionMove
	(*RepositionPlanResponse)(nil),    // 18: mittens.v1.RepositionPlanResponse
	(*ExplainDecisionRequest)(nil),    // 19: mittens.v1.ExplainDecisionRequest
	(*ArcExplanation)(nil),            // 20: mittens.v1.ArcExplanation
	(*ExplainDecisionResponse)(nil),   // 21: mittens.v1.ExplainDecisionResponse
	(*ReplayDecisionRequest)(nil),     // 22: mittens.v1.ReplayDecisionRequest
	(*ReplayDecisionResponse)(nil),    // 23: mittens.v1.ReplayDecisionResponse
	(*VerifyMerkleChainRequest)(nil),  // 24: mittens.v1.VerifyMerkleChainRequest
	(*VerifyMerkleChainResponse)(nil), // 25: mittens.v1.VerifyMerkleChainResponse
	nil,                               // 26: mittens.v1.DecisionProvenance.ActiveBeliefVectorEntry
	nil,                               // 27: mittens.v1.DecisionProvenance.PricingVariablesEntry
}
var file_proto_mittens_v1_optimizer_proto_depIdxs = []int32{
	0,  // 0: mittens.v1.Driver.current_location:type_name -> mittens.v1.Location
	0,  // 1: mittens.v1.Driver.home_location:type_name -> mittens.v1.Location
	1,  // 2: mittens.v1.Driver.equipment:type_name -> mittens.v1.Equipment
	0,  // 3: mittens.v1.Load.origin:type_name -> mittens.v1.Location
	0,  // 4: mittens.v1.Load.destination:type_name -> mittens.v1.Location
	8,  // 5: mittens.v1.DecisionProvenance.evaluated_arcs:type_name -> mittens.v1.CandidateEvaluation
	26, // 6: mittens.v1.DecisionProvenance.active_belief_vector:type_name -> mittens.v1.DecisionProvenance.ActiveBeliefVectorEntry
	27, // 7: mittens.v1.DecisionProvenance.pricing_variables:type_name -> mittens.v1.DecisionProvenance.PricingVariablesEntry
	2,  // 8: mittens.v1.OptimizeRequest.drivers:type_name -> mittens.v1.Driver
	3,  // 9: mittens.v1.OptimizeRequest.loads:type_name -> mittens.v1.Load
	4,  // 10: mittens.v1.OptimizeRequest.cost_config:type_name -> mittens.v1.CostConfig
	5,  // 11: mittens.v1.OptimizeRequest.feasibility_config:type_name -> mittens.v1.FeasibilityConfig
	6,  // 12: mittens.v1.OptimizeResponse.matches:type_name -> mittens.v1.Match
	7,  // 13: mittens.v1.OptimizeResponse.spot_bids:type_name -> mittens.v1.SpotBid
	9,  // 14: mittens.v1.OptimizeResponse.provenance:type_name -> mittens.v1.DecisionProvenance
	0,  // 15: mittens.v1.StreamTelemetryRequest.current_location:type_name -> mittens.v1.Location
	3,  // 16: mittens.v1.StreamTendersRequest.loads:type_name -> mittens.v1.Load
	2,  // 17: mittens.v1.RepositionPlanRequest.idle_drivers:type_name -> mittens.v1.Driver
	17, // 18: mittens.v1.RepositionPlanResponse.moves:type_name -> mittens.v1.RepositionMove
	20, // 19: mittens.v1.ExplainDecisionResponse.top_candidates:type_name -> mittens.v1.ArcExplanation
	10, // 20: mittens.v1.OptimizerService.Optimize:input_type -> mittens.v1.OptimizeRequest
	12, // 21: mittens.v1.OptimizerService.StreamTelemetry:input_type -> mittens.v1.StreamTelemetryRequest
	14, // 22: mittens.v1.OptimizerService.StreamTenders:input_type -> mittens.v1.StreamTendersRequest
	16, // 23: mittens.v1.OptimizerService.PlanRepositioning:input_type -> mittens.v1.RepositionPlanRequest
	19, // 24: mittens.v1.OptimizerService.ExplainDecision:input_type -> mittens.v1.ExplainDecisionRequest
	22, // 25: mittens.v1.OptimizerService.ReplayDecision:input_type -> mittens.v1.ReplayDecisionRequest
	24, // 26: mittens.v1.OptimizerService.VerifyMerkleChain:input_type -> mittens.v1.VerifyMerkleChainRequest
	11, // 27: mittens.v1.OptimizerService.Optimize:output_type -> mittens.v1.OptimizeResponse
	13, // 28: mittens.v1.OptimizerService.StreamTelemetry:output_type -> mittens.v1.StreamTelemetryResponse
	15, // 29: mittens.v1.OptimizerService.StreamTenders:output_type -> mittens.v1.StreamTendersResponse
	18, // 30: mittens.v1.OptimizerService.PlanRepositioning:output_type -> mittens.v1.RepositionPlanResponse
	21, // 31: mittens.v1.OptimizerService.ExplainDecision:output_type -> mittens.v1.ExplainDecisionResponse
	23, // 32: mittens.v1.OptimizerService.ReplayDecision:output_type -> mittens.v1.ReplayDecisionResponse
	25, // 33: mittens.v1.OptimizerService.VerifyMerkleChain:output_type -> mittens.v1.VerifyMerkleChainResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_mittens_v1_optimizer_proto_init() }
func file_proto_mittens_v1_optimizer_proto_init() {
	if File_proto_mittens_v1_optimizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mittens_v1_optimizer_proto_rawDesc), len(file_proto_mittens_v1_optimizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mittens_v1_optimizer_proto_goTypes,
		DependencyIndexes: file_proto_mittens_v1_optimizer_proto_depIdxs,
		MessageInfos:      file_proto_mittens_v1_optimizer_proto_msgTypes,
	}.Build()
	File_proto_mittens_v1_optimizer_proto = out.File
	file_proto_mittens_v1_optimizer_proto_goTypes = nil
	file_proto_mittens_v1_optimizer_proto_depIdxs = nil
}
